// vueclient/src/components/ChannelControls.vue
<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<script setup lang="ts">
import { useWebRTC, type PeerConnection } from '@/composible/useWebRTC'
import {
  faChevronUp,
  faDisplay,
  faMicrophone,
  faMicrophoneSlash,
  faPhoneSlash,
  faStop,
  faVideo,
  faVideoSlash,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { ref } from 'vue'

const props = defineProps<{
  videoEnabled: boolean
  audioEnabled: boolean
  isScreenSharing: boolean
  startScreenShare: any
  stopScreenShare: any
  videoStreamIndex: number
  localStream: MediaStream | null
  currentCameraDeviceId: string | null
  currentMicrophoneDeviceId: string | null
  remotePeers: PeerConnection[]
}>()

const emits = defineEmits<{
  (e: 'endCall'): void
  (e: 'update:videoEnabled', value: boolean): void
  (e: 'update:audioEnabled', value: boolean): void
  (e: 'update:videoStreamIndex', value: number): void
  (e: 'update:selectCamera', value: string): void
  (e: 'update:currentCameraDeviceId', value: string): void
  (e: 'update:selectMicrophone', value: string): void
  (e: 'update:toggleMicrophone'): void
  (e: 'update:toggleVideo'): void
}>()

const { videoDevices, audioDevices, fetchVideoDevices, fetchAudioDevices } = useWebRTC()

const cameraMenuOpen = ref(false)
const microphoneMenuOpen = ref(false)

// Переключение состояния видео
function toggleVideo() {
  emits('update:toggleVideo')
}

function selectCamera(deviceId: string) {
  emits('update:selectCamera', deviceId)
  emits('update:currentCameraDeviceId', deviceId)
  cameraMenuOpen.value = false
}

// Переключение состояния микрофона
function toggleAudio() {
  // Просим родительский компонент выполнить фактическое переключение микрофона (он управляет треками и состоянием)
  emits('update:toggleMicrophone')
  // Обновляем булево значение в родителе, чтобы интерфейс оставался синхронизирован
  emits('update:audioEnabled', !props.audioEnabled)
}

// Переключение меню выбора камеры
async function toggleCameraMenu() {
  cameraMenuOpen.value = !cameraMenuOpen.value
  if (cameraMenuOpen.value) {
    // Загружаем список видеоустройств
    fetchVideoDevices()
  }
}

// Переключение меню выбора микрофона
function toggleMicrophoneMenu() {
  microphoneMenuOpen.value = !microphoneMenuOpen.value
  if (microphoneMenuOpen.value) {
    // Загружаем список аудиоустройств
    fetchAudioDevices()
  }
}

function deviceAudioIndex(device: MediaDeviceInfo) {
  return audioDevices.value.indexOf(device) + 1
}

function deviceVideoIndex(device: MediaDeviceInfo) {
  return videoDevices.value.indexOf(device) + 1
}

function selectMicrophone(deviceId: string) {
  emits('update:selectMicrophone', deviceId)
  microphoneMenuOpen.value = false
}
</script>

<template>
  <div class="p-2 sm:p-4 bg-slate-900/50 border-t border-slate-800">
    <div class="flex items-center justify-center gap-2 sm:gap-4 flex-wrap">
      <div class="relative flex items-center">
        <!-- Основная кнопка включения/выключения видео -->
        <button
          type="button"
          :class="[
            'p-3 sm:p-4 rounded-l-full transition-all flex items-center justify-center touch-manipulation active:scale-95',
            props.videoEnabled ? 'bg-slate-700 hover:bg-slate-600' : 'bg-red-600 hover:bg-red-700',
          ]"
          @click="toggleVideo"
          :title="props.videoEnabled ? 'Отключить видео' : 'Включить видео'"
        >
          <FontAwesomeIcon
            :icon="props.videoEnabled ? faVideo : faVideoSlash"
            class="text-lg sm:text-xl text-white"
          />
        </button>

        <!-- Кнопка выбора камеры -->
        <div class="relative">
          <button
            type="button"
            class="p-3 sm:p-4 rounded-r-full bg-slate-700 hover:bg-slate-600 active:bg-slate-500 transition-all flex items-center justify-center touch-manipulation active:scale-95"
            @click="toggleCameraMenu"
            title="Выбрать камеру"
          >
            <FontAwesomeIcon
              :icon="faChevronUp"
              class="text-lg sm:text-xl text-white"
              :class="{ 'rotate-180': cameraMenuOpen }"
            />
          </button>

          <!-- Выпадающее меню для выбора камеры -->
          <transition name="fade">
            <ul
              v-if="cameraMenuOpen"
              class="absolute right-0 bottom-12 mt-2 w-48 sm:w-56 bg-slate-800 text-white rounded-xl shadow-lg z-50 max-h-48 overflow-y-auto"
              v-click-outside="() => (cameraMenuOpen = false)"
            >
              <li
                v-for="device in videoDevices"
                :key="device.deviceId"
                class="px-3 sm:px-4 py-2 text-sm sm:text-base rounded-xl hover:bg-slate-700 active:bg-slate-600 cursor-pointer transition-colors touch-manipulation"
                :class="{ 'bg-slate-600': currentCameraDeviceId === device.deviceId }"
                @click="selectCamera(device.deviceId)"
              >
                {{ device.label || 'Камера ' + deviceVideoIndex(device) }}
              </li>
            </ul>
          </transition>
        </div>
      </div>

      <div class="relative flex justify-center items-center">
        <button
          type="button"
          :class="[
            'p-3 sm:p-4 rounded-l-full transition-all flex items-center justify-center touch-manipulation active:scale-95',
            props.audioEnabled ? 'bg-slate-700 hover:bg-slate-600' : 'bg-red-600 hover:bg-red-700',
          ]"
          @click="toggleAudio"
          :title="props.audioEnabled ? 'Отключить микрофон' : 'Включить микрофон'"
        >
          <FontAwesomeIcon
            :icon="props.audioEnabled ? faMicrophone : faMicrophoneSlash"
            class="text-lg sm:text-xl text-white"
          />
        </button>

        <div class="relative">
          <button
            type="button"
            class="p-3 sm:p-4 rounded-r-full bg-slate-700 hover:bg-slate-600 active:bg-slate-500 transition-all flex items-center justify-center touch-manipulation active:scale-95"
            @click="toggleMicrophoneMenu"
            title="Выбрать микрофон"
          >
            <FontAwesomeIcon
              :icon="faChevronUp"
              class="text-lg sm:text-xl text-white"
              :class="{ 'rotate-180': microphoneMenuOpen }"
            />
          </button>
        </div>

        <!-- Выпадающее меню -->
        <transition name="fade">
          <ul
            v-if="microphoneMenuOpen"
            class="absolute right-0 bottom-12 mt-2 w-48 sm:w-56 bg-slate-800 text-white rounded-xl shadow-lg z-50 items-center justify-center max-h-48 overflow-y-auto"
            v-click-outside="() => (microphoneMenuOpen = false)"
          >
            <li
              v-for="device in audioDevices"
              :key="device.deviceId"
              :class="{ 'bg-slate-600': currentMicrophoneDeviceId === device.deviceId }"
              @click="selectMicrophone(device.deviceId)"
              class="px-3 sm:px-4 py-2 text-sm sm:text-base rounded-xl hover:bg-slate-700 active:bg-slate-600 cursor-pointer transition-colors touch-manipulation"
            >
              {{ device.label || 'Микрофон ' + deviceAudioIndex(device) }}
            </li>
          </ul>
        </transition>
      </div>

      <button
        type="button"
        class="p-3 sm:p-4 flex items-center justify-center rounded-full bg-slate-700 hover:bg-slate-600 active:bg-slate-500 transition-all touch-manipulation active:scale-95"
        @click="isScreenSharing ? stopScreenShare() : startScreenShare()"
        :title="isScreenSharing ? 'Остановить демонстрацию экрана' : 'Начать демонстрацию экрана'"
      >
        <FontAwesomeIcon
          :icon="isScreenSharing ? faStop : faDisplay"
          class="text-lg sm:text-xl text-white"
        ></FontAwesomeIcon>
      </button>

      <button
        type="button"
        class="p-3 sm:p-4 flex items-center justify-center rounded-full bg-red-600 hover:bg-red-700 active:bg-red-800 transition-all touch-manipulation active:scale-95 shadow-lg"
        @click="emits('endCall')"
        title="Завершить звонок"
      >
        <FontAwesomeIcon :icon="faPhoneSlash" class="text-lg sm:text-xl text-white" />
      </button>
    </div>

    <div class="mt-2 sm:mt-4 text-center text-xs sm:text-sm text-slate-400 px-2">
      <p>Участников: {{ remotePeers.length + 1 }}</p>
    </div>
  </div>
</template>

// electron-client/src/components/ChannelControls.tsx
import { useState, useEffect } from 'react'
import { FontAwesomeIcon } from '@/icons'
import {
  faChevronUp,
  faDisplay,
  faMicrophone,
  faMicrophoneSlash,
  faMusic,
  faPhoneSlash,
  faStop,
  faVideo,
  faVideoSlash,
  faCircleExclamation,
} from '@/icons'
import type { ScreenAudioStatus } from '@/hooks/useWebRTC'

type Props = {
  videoEnabled: boolean
  audioEnabled: boolean
  isScreenSharing: boolean
  screenAudioStatus: ScreenAudioStatus
  screenAudioLevel: number
  startScreenShare: (options?: import('@/hooks/useWebRTC').ScreenShareOptions) => void
  stopScreenShare: () => void
  onOpenScreenShareModal?: () => void
  currentCameraDeviceId: string | null
  currentMicrophoneDeviceId: string | null
  remotePeersCount: number
  onEndCall: () => void
  onToggleVideo: () => void
  onToggleMicrophone: () => void
  onSelectCamera: (deviceId: string) => void
  onSelectMicrophone: (deviceId: string) => void
  videoDevices: MediaDeviceInfo[]
  audioDevices: MediaDeviceInfo[]
  fetchVideoDevices: () => Promise<void>
  fetchAudioDevices: () => Promise<void>
}

export default function ChannelControls({
  videoEnabled,
  audioEnabled,
  isScreenSharing,
  screenAudioStatus,
  screenAudioLevel,
  startScreenShare,
  stopScreenShare,
  onOpenScreenShareModal,
  currentCameraDeviceId,
  currentMicrophoneDeviceId,
  remotePeersCount,
  onEndCall,
  onToggleVideo,
  onToggleMicrophone,
  onSelectCamera,
  onSelectMicrophone,
  videoDevices,
  audioDevices,
  fetchVideoDevices,
  fetchAudioDevices,
}: Props) {
  const [cameraMenuOpen, setCameraMenuOpen] = useState(false)
  const [microphoneMenuOpen, setMicrophoneMenuOpen] = useState(false)

  useEffect(() => {
    if (cameraMenuOpen) fetchVideoDevices()
  }, [cameraMenuOpen, fetchVideoDevices])
  useEffect(() => {
    if (microphoneMenuOpen) fetchAudioDevices()
  }, [microphoneMenuOpen, fetchAudioDevices])

  return (
    <div className="p-4 bg-slate-900/50 border-t border-slate-800">
      <div className="flex items-center justify-center gap-4 flex-wrap">
        <div className="relative flex items-center">
          <button
            type="button"
            onClick={onToggleVideo}
            className={`p-4 rounded-l-full transition-colors ${
              videoEnabled ? 'bg-slate-700 hover:bg-slate-600' : 'bg-red-600 hover:bg-red-700'
            }`}
            title={videoEnabled ? 'Выключить видео' : 'Включить видео'}
          >
            <FontAwesomeIcon icon={videoEnabled ? faVideo : faVideoSlash} className="text-lg text-white" />
          </button>
          <button
            type="button"
            onClick={() => setCameraMenuOpen(!cameraMenuOpen)}
            className="p-4 rounded-r-full bg-slate-700 hover:bg-slate-600"
            title="Выбрать камеру"
          >
            <FontAwesomeIcon icon={faChevronUp} className={`text-lg text-white transition-transform ${cameraMenuOpen ? 'rotate-180' : ''}`} />
          </button>
          {cameraMenuOpen && (
            <>
              <div className="fixed inset-0 z-40" onClick={() => setCameraMenuOpen(false)} />
              <ul className="absolute right-0 bottom-14 w-56 bg-slate-800 text-white rounded-xl shadow-lg z-50 max-h-48 overflow-y-auto py-2">
                {videoDevices.map((d) => (
                  <li
                    key={d.deviceId}
                    onClick={() => {
                      onSelectCamera(d.deviceId)
                      setCameraMenuOpen(false)
                    }}
                    className={`px-4 py-2 cursor-pointer hover:bg-slate-700 ${
                      currentCameraDeviceId === d.deviceId ? 'bg-slate-600' : ''
                    }`}
                  >
                    {d.label || `Камера ${videoDevices.indexOf(d) + 1}`}
                  </li>
                ))}
              </ul>
            </>
          )}
        </div>

        <div className="relative flex items-center">
          <button
            type="button"
            onClick={onToggleMicrophone}
            className={`p-4 rounded-l-full transition-colors ${
              audioEnabled ? 'bg-slate-700 hover:bg-slate-600' : 'bg-red-600 hover:bg-red-700'
            }`}
            title={audioEnabled ? 'Выключить микрофон' : 'Включить микрофон'}
          >
            <FontAwesomeIcon icon={audioEnabled ? faMicrophone : faMicrophoneSlash} className="text-lg text-white" />
          </button>
          <button
            type="button"
            onClick={() => setMicrophoneMenuOpen(!microphoneMenuOpen)}
            className="p-4 rounded-r-full bg-slate-700 hover:bg-slate-600"
            title="Выбрать микрофон"
          >
            <FontAwesomeIcon icon={faChevronUp} className={`text-lg text-white transition-transform ${microphoneMenuOpen ? 'rotate-180' : ''}`} />
          </button>
          {microphoneMenuOpen && (
            <>
              <div className="fixed inset-0 z-40" onClick={() => setMicrophoneMenuOpen(false)} />
              <ul className="absolute right-0 bottom-14 w-56 bg-slate-800 text-white rounded-xl shadow-lg z-50 max-h-48 overflow-y-auto py-2">
                {audioDevices.map((d) => (
                  <li
                    key={d.deviceId}
                    onClick={() => {
                      onSelectMicrophone(d.deviceId)
                      setMicrophoneMenuOpen(false)
                    }}
                    className={`px-4 py-2 cursor-pointer hover:bg-slate-700 ${
                      currentMicrophoneDeviceId === d.deviceId ? 'bg-slate-600' : ''
                    }`}
                  >
                    {d.label || `Микрофон ${audioDevices.indexOf(d) + 1}`}
                  </li>
                ))}
              </ul>
            </>
          )}
        </div>

        <button
          type="button"
          onClick={
            isScreenSharing
              ? stopScreenShare
              : onOpenScreenShareModal
                ? onOpenScreenShareModal
                : () => startScreenShare()
          }
          className={`p-4 rounded-full transition-colors ${
            isScreenSharing
              ? 'bg-sky-600 hover:bg-sky-700'
              : 'bg-slate-700 hover:bg-slate-600'
          }`}
          title={isScreenSharing ? 'Остановить демонстрацию экрана' : 'Демонстрация экрана'}
        >
          <FontAwesomeIcon icon={isScreenSharing ? faStop : faDisplay} className="text-lg text-white" />
        </button>

        <button
          type="button"
          onClick={onEndCall}
          className="p-4 rounded-full bg-red-600 hover:bg-red-700"
          title="Завершить звонок"
        >
          <FontAwesomeIcon icon={faPhoneSlash} className="text-lg text-white" />
        </button>
      </div>
      <div className="mt-2 flex items-center justify-center gap-3 text-xs">
        <span className="text-slate-400">Участников: {remotePeersCount + 1}</span>
        {isScreenSharing && screenAudioStatus === 'capturing' && (
          <span className="flex items-center gap-1.5 text-green-400" title="Аудио экрана передаётся">
            <FontAwesomeIcon icon={faMusic} className="text-[10px]" />
            <span>Аудио</span>
            {/* VU-meter bar */}
            <span className="inline-flex items-end gap-px h-3">
              {[0.15, 0.3, 0.5, 0.7, 0.9].map((thresh, i) => (
                <span
                  key={i}
                  className={`w-[3px] rounded-sm transition-all duration-75 ${
                    screenAudioLevel >= thresh ? 'bg-green-400' : 'bg-slate-600'
                  }`}
                  style={{ height: `${4 + i * 2}px` }}
                />
              ))}
            </span>
          </span>
        )}
        {isScreenSharing && screenAudioStatus === 'failed' && (
          <span className="flex items-center gap-1 text-red-400" title="Не удалось захватить аудио экрана">
            <FontAwesomeIcon icon={faCircleExclamation} className="text-[10px]" />
            <span>Аудио не захвачено</span>
          </span>
        )}
        {isScreenSharing && screenAudioStatus === 'no-driver' && (
          <span className="flex items-center gap-1 text-amber-400" title="Нужен виртуальный аудиодрайвер (BlackHole)">
            <FontAwesomeIcon icon={faCircleExclamation} className="text-[10px]" />
            <span>Нет аудиодрайвера</span>
          </span>
        )}
      </div>
    </div>
  )
}
