// electron-client/src/components/Sidebar.tsx
import { useState, useEffect, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { AuthService, SignalingService } from '@/api'
import type { UserProfile, Room } from '@/api'
import { useAuthStore } from '@/stores/authStore'
import { useRoomStore } from '@/stores/roomStore'
import { useSidebarStore } from '@/stores/sidebarStore'
import { useApiErrors } from '@/hooks/useApiErrors'
import { FontAwesomeIcon } from '@/icons'
import { faCheck, faHashtag, faPlus, faSignOutAlt, faSync, faTimes, faUser, faXmark } from '@/icons'

export default function Sidebar({ user }: { user: UserProfile }) {
  const navigate = useNavigate()
  const [showCreateInput, setShowCreateInput] = useState(false)
  const [newChannelName, setNewChannelName] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const authStore = useAuthStore.getState()
  const roomStore = useRoomStore()
  const sidebarStore = useSidebarStore()
  const { parseApiError, clearErrors } = useApiErrors()

  const channels = roomStore.channels
  const selectedChannelId = roomStore.selectedChannelId
  const filteredChannels = searchQuery.trim()
    ? channels.filter((ch) => ch.name?.toLowerCase().includes(searchQuery.toLowerCase()))
    : channels

  const refreshChannels = useCallback(async () => {
    setIsLoading(true)
    try {
      await roomStore.getListChannels()
    } catch (e) {
      parseApiError(e)
    } finally {
      setIsLoading(false)
    }
  }, [roomStore, parseApiError])

  const addChannel = useCallback(async () => {
    if (!newChannelName.trim()) return
    clearErrors()
    setIsLoading(true)
    try {
      await SignalingService.createRoom({ name: newChannelName.trim() })
      await roomStore.getListChannels()
      setNewChannelName('')
      setShowCreateInput(false)
      setSearchQuery('')
    } catch (e) {
      parseApiError(e)
    } finally {
      setIsLoading(false)
    }
  }, [newChannelName, roomStore, parseApiError, clearErrors])

  const selectChannel = useCallback(
    (channelId: string, roommates?: string[]) => {
      roomStore.selectChannel(channelId, roommates)
      sidebarStore.close()
    },
    [roomStore, sidebarStore]
  )

  const logout = useCallback(async () => {
    try {
      await AuthService.logoutUser()
    } catch (e) {
      console.warn('Logout API failed', e)
    }
    authStore.clearTokens()
    navigate('/auth/login')
    window.location.reload()
  }, [navigate, authStore])

  useEffect(() => {
    useSidebarStore.getState().checkMobile()
    useRoomStore.getState().getListChannels().catch((e) => console.error(e))
    const onResize = () => useSidebarStore.getState().checkMobile()
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [])

  return (
    <>
      {sidebarStore.isMobile && sidebarStore.isOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 md:hidden"
          onClick={() => sidebarStore.close()}
          aria-hidden
        />
      )}
      <aside
        data-sidebar
        className={`fixed md:static inset-y-0 left-0 z-40 flex flex-col bg-slate-900/95 border-r border-slate-800 w-[260px] min-w-[260px] sm:w-[280px] sm:min-w-[280px] xl:w-[320px] xl:min-w-[320px] flex-shrink-0 transition-transform duration-300 ${
          sidebarStore.isMobile ? (sidebarStore.isOpen ? 'translate-x-0' : '-translate-x-full') : ''
        }`}
      >
        <header className="flex items-center justify-between p-4 border-b border-slate-800 flex-shrink-0">
          <div>
            <h1 className="text-lg font-bold text-white">Каналы</h1>
            <p className="text-xs text-slate-400">{filteredChannels.length} каналов</p>
          </div>
          {sidebarStore.isMobile && (
            <button
              onClick={() => sidebarStore.close()}
              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800"
              aria-label="Закрыть"
            >
              <FontAwesomeIcon icon={faTimes} />
            </button>
          )}
        </header>

        <div className="p-3 border-b border-slate-800 space-y-2">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Поиск каналов..."
            className="w-full px-4 py-2 bg-slate-800 border border-slate-700 rounded-lg text-white placeholder-slate-500 text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
          />
          <div className="flex gap-2">
            <button
              onClick={refreshChannels}
              disabled={isLoading}
              className="flex-1 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-sm font-medium disabled:opacity-50 flex items-center justify-center gap-2"
            >
              <FontAwesomeIcon icon={faSync} className={isLoading ? 'animate-spin' : ''} /> Обновить
            </button>
            <button
              onClick={() => setShowCreateInput(!showCreateInput)}
              className="px-3 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium"
            >
              <FontAwesomeIcon icon={faPlus} />
            </button>
          </div>
          {showCreateInput && (
            <div className="p-3 bg-slate-800/50 rounded-lg border border-slate-700 space-y-2">
              <input
                value={newChannelName}
                onChange={(e) => setNewChannelName(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addChannel()}
                placeholder="Название канала"
                className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-lg text-white text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                autoFocus
              />
              <div className="flex gap-2">
                <button
                  onClick={addChannel}
                  disabled={!newChannelName.trim() || isLoading}
                  className="flex-1 px-3 py-2 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white rounded-lg text-sm font-medium flex items-center justify-center gap-2"
                >
                  <FontAwesomeIcon icon={faCheck} /> Создать
                </button>
                <button
                  onClick={() => { setShowCreateInput(false); setNewChannelName('') }}
                  className="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg text-sm"
                >
                  <FontAwesomeIcon icon={faXmark} />
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="flex-1 overflow-y-auto p-2">
          {!isLoading && filteredChannels.length === 0 && (
            <div className="flex flex-col items-center justify-center py-12 text-center text-slate-400">
              <p className="font-medium">{searchQuery ? 'Каналы не найдены' : 'Нет каналов'}</p>
              <p className="text-sm">{searchQuery ? 'Попробуйте другой запрос' : 'Создайте первый канал'}</p>
            </div>
          )}
          {isLoading && channels.length === 0 && (
            <div className="flex justify-center py-12 text-slate-400">Загрузка...</div>
          )}
          <ul className="space-y-1">
            {filteredChannels.map((ch) => (
              <li key={String(ch?.id ?? '')}>
                {ch.id != null && (
                  <button
                    onClick={() => selectChannel(String(ch.id), (ch as Room).roommates)}
                    className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left text-sm font-medium transition-colors ${
                      String(ch.id) === selectedChannelId
                        ? 'bg-indigo-600/20 text-indigo-300 border-l-4 border-indigo-500'
                        : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                    }`}
                  >
                    <FontAwesomeIcon icon={faHashtag} className="flex-shrink-0 text-slate-500" />
                    <span className="flex-1 truncate">{ch.name || 'Без названия'}</span>
                    {((ch as Room).roommates?.length ?? 0) > 0 && (
                      <span className="px-2 py-0.5 rounded-full text-xs bg-slate-700 text-slate-300">
                        {(ch as Room).roommates!.length}
                      </span>
                    )}
                  </button>
                )}
              </li>
            ))}
          </ul>
        </div>

        <div className="p-4 border-t border-slate-800 flex-shrink-0">
          <div className="flex items-center gap-3 mb-4 p-3 rounded-lg bg-slate-800/50">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-cyan-600 flex items-center justify-center text-white font-semibold text-sm">
              <FontAwesomeIcon icon={faUser} />
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-semibold text-white truncate">{user.username || 'User'}</p>
              <p className="text-xs text-slate-400">Онлайн</p>
            </div>
          </div>
          <button
            onClick={logout}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-red-600/20 hover:bg-red-600/30 text-red-400 rounded-lg text-sm font-medium border border-red-600/30"
          >
            <FontAwesomeIcon icon={faSignOutAlt} /> Выйти
          </button>
        </div>
      </aside>
    </>
  )
}

// vueclient/src/widgets/sidebar/Sidebar.vue
<script setup lang="ts">
import { SignalingService, type UserProfile } from '@/api/index'
import { useApiErrors } from '@/shared/lib/useApiErrors'
import { useRoomStore } from '@/shared/stores/roomStore'
import { useSidebarStore } from '@/shared/stores/sidebarStore'
import { useCallStore } from '@/shared/stores/callStore'
import { useVoiceStateStore } from '@/shared/stores/voiceStateStore'
import UserPanel from '@/widgets/user-panel/UserPanel.vue'
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const { clearErrors, parseApiError } = useApiErrors()
const roomStore = useRoomStore()
const sidebarStore = useSidebarStore()
const callStore = useCallStore()
const voiceStateStore = useVoiceStateStore()

const props = defineProps<{ user: UserProfile }>()

const showCreateInput = ref(false)
const newChannelName = ref('')
const searchQuery = ref('')
const isLoading = ref(false)

const filteredChannels = computed(() => {
  if (!searchQuery.value.trim()) return roomStore.channels
  const q = searchQuery.value.toLowerCase()
  return roomStore.channels.filter((ch) => ch.name?.toLowerCase().includes(q))
})

async function addChannel() {
  if (!newChannelName.value.trim()) return
  clearErrors()
  isLoading.value = true
  try {
    await SignalingService.createRoom({ name: newChannelName.value.trim() })
    await roomStore.getListChannels()
    newChannelName.value = ''
    showCreateInput.value = false
    searchQuery.value = ''
  } catch (e) {
    parseApiError(e)
  } finally {
    isLoading.value = false
  }
}

function selectChannel(channelId: string | undefined, roommates?: string[]) {
  if (!channelId) return
  roomStore.selectChannel(channelId, roommates)
  sidebarStore.close()
}

async function refreshChannels() {
  isLoading.value = true
  try {
    await roomStore.getListChannels()
  } catch (e) {
    parseApiError(e)
  } finally {
    isLoading.value = false
  }
}

function handleResize() {
  sidebarStore.checkMobile()
}

function getInitials(name: string): string {
  return name.charAt(0).toUpperCase()
}

function getAvatarColor(name: string): string {
  const colors = [
    '#5865f2', '#57f287', '#fee75c', '#eb459e',
    '#ed4245', '#f47b67', '#e78284', '#3ba55d',
  ]
  let hash = 0
  for (let i = 0; i < name.length; i++) hash = name.charCodeAt(i) + ((hash << 5) - hash)
  return colors[Math.abs(hash) % colors.length]
}

onMounted(() => {
  sidebarStore.checkMobile()
  window.addEventListener('resize', handleResize)
  refreshChannels()
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
})

watch(
  () => roomStore.selectedChannelId,
  () => sidebarStore.close(),
)
</script>

<template>
  <!-- Overlay for mobile -->
  <Transition name="fade">
    <div
      v-if="sidebarStore.isMobile && sidebarStore.isOpen"
      class="fixed inset-0 bg-black/60 z-40 lg:hidden"
      @click="sidebarStore.close"
    />
  </Transition>

  <aside
    :class="[
      'fixed lg:static inset-y-0 left-0 z-40 flex flex-col bg-dc-bg-secondary transition-transform duration-200 ease-out',
      sidebarStore.isMobile
        ? sidebarStore.isOpen ? 'translate-x-0 w-[280px]' : '-translate-x-full w-[280px]'
        : 'translate-x-0 w-60 2xl:w-[272px]',
    ]"
  >
    <!-- Server header -->
    <div
      class="h-12 2xl:h-14 px-4 flex items-center shadow-[0_1px_0_rgba(4,4,5,0.2),0_1.5px_0_rgba(6,6,7,0.05),0_2px_0_rgba(4,4,5,0.05)] flex-shrink-0 hover:bg-dc-bg-hover transition-colors cursor-pointer"
    >
      <h1 class="text-[15px] font-semibold text-dc-text-heading truncate flex-1">
        {{ t('sidebar.appTitle') }}
      </h1>
      <button
        v-if="sidebarStore.isMobile"
        @click="sidebarStore.close"
        class="w-7 h-7 flex items-center justify-center text-dc-text-muted hover:text-dc-text transition-colors lg:hidden"
      >
        <font-awesome-icon icon="xmark" class="text-lg" />
      </button>
    </div>

    <!-- Channel list -->
    <div class="flex-1 overflow-y-auto pt-4 dc-scrollbar-thin">
      <!-- Search (compact) -->
      <div v-if="searchQuery || roomStore.channels.length > 5" class="px-2 mb-2">
        <input
          v-model="searchQuery"
          type="text"
          :placeholder="t('common.search')"
          class="w-full px-2 py-1 rounded bg-dc-bg-tertiary text-dc-text text-sm placeholder-dc-text-muted border-none outline-none focus:ring-1 focus:ring-dc-blurple/40"
        />
      </div>

      <!-- Category header -->
      <div class="flex items-center px-2 mb-1 group cursor-pointer" @click="showCreateInput = !showCreateInput">
        <font-awesome-icon icon="chevron-down" class="w-3 h-3 text-dc-text-muted mr-0.5 text-[10px]" />
        <span class="text-[11px] font-bold uppercase tracking-wider text-dc-text-muted group-hover:text-dc-text-secondary flex-1">
          {{ t('common.voiceChannels') }}
        </span>
        <button
          class="w-4 h-4 flex items-center justify-center text-dc-text-muted hover:text-dc-text-secondary opacity-0 group-hover:opacity-100 transition-opacity"
          :title="t('common.createChannel')"
          @click.stop="showCreateInput = !showCreateInput"
        >
          <font-awesome-icon icon="plus" class="text-xs" />
        </button>
      </div>

      <!-- Create channel input -->
      <Transition name="slide-down">
        <div v-if="showCreateInput" class="px-2 mb-2">
          <div class="flex gap-1">
            <input
              v-model="newChannelName"
              @keyup.enter="addChannel"
              @keyup.escape="showCreateInput = false; newChannelName = ''"
              type="text"
              :placeholder="t('common.channelNamePlaceholder')"
              autofocus
              class="flex-1 px-2 py-1.5 rounded bg-dc-bg-tertiary text-dc-text text-sm placeholder-dc-text-muted border-none outline-none focus:ring-1 focus:ring-dc-blurple/40"
            />
            <button
              @click="addChannel"
              :disabled="!newChannelName.trim() || isLoading"
              class="px-2 py-1.5 rounded bg-dc-green hover:bg-dc-green/80 disabled:opacity-40 text-white text-xs font-medium transition-colors"
            >
              {{ t('common.ok') }}
            </button>
          </div>
        </div>
      </Transition>

      <!-- Loading -->
      <div v-if="isLoading && roomStore.channels.length === 0" class="px-2 py-8 text-center">
        <div class="text-dc-text-muted text-sm">{{ t('sidebar.loadingChannels') }}</div>
      </div>

      <!-- Empty -->
      <div
        v-else-if="filteredChannels.length === 0"
        class="px-2 py-8 text-center"
      >
        <div class="text-dc-text-muted text-sm">
          {{ searchQuery ? t('common.noChannelsFound') : t('common.noChannelsYet') }}
        </div>
      </div>

      <!-- Channel items -->
      <div v-else class="px-2 space-y-px">
        <div v-for="ch in filteredChannels" :key="ch.id || ''">
          <!-- Channel button -->
          <button
            @click="selectChannel(ch.id, ch.roommates)"
            :class="[
              'w-full flex items-center gap-1.5 px-2 py-[6px] rounded group transition-colors text-left',
              ch.id === roomStore.selectedChannelId
                ? 'bg-dc-bg-active text-dc-text-heading'
                : 'text-dc-text-muted hover:text-dc-text-secondary hover:bg-dc-bg-hover',
            ]"
          >
            <font-awesome-icon icon="volume-high" class="w-5 h-5 flex-shrink-0 opacity-70 text-[16px]" />
            <span class="flex-1 text-[15px] truncate font-medium leading-5">{{ ch.name || t('common.unnamed') }}</span>
          </button>

          <!-- Participants list under channel -->
          <div
            v-if="ch.roommates && ch.roommates.length > 0"
            class="ml-[22px] pl-2 border-l border-dc-bg-active/30"
          >
            <div
              v-for="mate in ch.roommates"
              :key="mate"
              class="flex items-center gap-2 py-[3px] px-1.5 rounded group/user hover:bg-dc-bg-hover/50 transition-colors"
            >
              <!-- Avatar with speaking indicator -->
              <div class="relative flex-shrink-0">
                <div
                  :class="[
                    'w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-semibold text-white transition-all duration-200',
                    voiceStateStore.isSpeaking(mate)
                      ? 'ring-[2.5px] ring-dc-green'
                      : '',
                  ]"
                  :style="{ backgroundColor: getAvatarColor(mate) }"
                >
                  {{ getInitials(mate) }}
                </div>
                <!-- Connecting indicator -->
                <div
                  v-if="voiceStateStore.isConnecting(mate)"
                  class="absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full bg-dc-blurple border-2 border-dc-bg-secondary-alt flex items-center justify-center"
                >
                  <div class="w-1.5 h-1.5 bg-white rounded-full animate-pulse" />
                </div>
              </div>

              <!-- Username -->
              <span
                :class="[
                  'flex-1 text-[13px] leading-4 truncate transition-colors',
                  voiceStateStore.isSpeaking(mate) ? 'text-dc-text-heading' : 'text-dc-text-secondary',
                ]"
              >
                {{ mate }}
                <span
                  v-if="voiceStateStore.isConnecting(mate)"
                  class="ml-1.5 text-[10px] text-dc-text-muted"
                >
                  {{ t('common.connecting') }}
                </span>
              </span>

              <!-- Screen sharing badge -->
              <span
                v-if="voiceStateStore.isScreenSharing(mate)"
                class="flex items-center gap-0.5 px-1 py-px rounded bg-dc-red/20 text-dc-red text-[9px] font-bold uppercase leading-none flex-shrink-0"
              >
                <font-awesome-icon icon="desktop" class="text-[8px]" />
                {{ t('common.live') }}
              </span>

              <!-- Muted mic icon -->
              <font-awesome-icon
                v-if="voiceStateStore.isMuted(mate)"
                icon="microphone-slash"
                class="text-[11px] flex-shrink-0 text-dc-red/80"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Refresh -->
      <div class="px-2 mt-4">
        <button
          @click="refreshChannels"
          :disabled="isLoading"
          class="w-full flex items-center justify-center gap-1 px-2 py-1 text-[11px] text-dc-text-muted hover:text-dc-text-secondary transition-colors"
        >
          <font-awesome-icon icon="arrows-rotate" :class="['text-[10px]', { 'animate-spin': isLoading }]" />
          {{ t('common.refresh') }}
        </button>
      </div>
    </div>

    <!-- Voice connected indicator -->
    <div
      v-if="callStore.isInCall && roomStore.selectedChannelName"
      class="px-3 py-2 bg-dc-bg-secondary-alt border-t border-white/[0.04]"
    >
      <div class="flex items-center gap-2">
        <div class="relative">
          <font-awesome-icon icon="volume-high" class="text-dc-green text-[16px]" />
          <div class="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-dc-green border-2 border-dc-bg-secondary-alt" />
        </div>
        <div class="flex-1 min-w-0">
          <div class="text-xs font-semibold text-dc-green leading-tight">{{ t('common.voiceConnected') }}</div>
          <div class="text-[11px] text-dc-text-muted truncate leading-tight">{{ roomStore.selectedChannelName }}</div>
        </div>
        <button
          @click="callStore.requestDisconnect()"
          class="w-7 h-7 flex items-center justify-center rounded hover:bg-dc-bg-hover text-dc-text-muted hover:text-dc-red transition-colors"
          :title="t('common.disconnect')"
        >
          <font-awesome-icon icon="phone-slash" class="text-sm" />
        </button>
      </div>
    </div>

    <!-- User panel -->
    <UserPanel :username="props.user.username || ''" />
  </aside>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.2s ease;
  overflow: hidden;
}
.slide-down-enter-from,
.slide-down-leave-to {
  max-height: 0;
  opacity: 0;
}
.slide-down-enter-to,
.slide-down-leave-from {
  max-height: 100px;
  opacity: 1;
}
</style>
