// vueclient/src/views/Identity/RegisterPage.vue
<script setup lang="ts">
import { AuthService, type AuthTokens, type RegisterRequest } from '@/api/index'
import { useApiErrors } from '@/composible/useApiErrors'
import { useAuthStore } from '@/stores/authStore'
import { faEye, faEyeSlash, faUser } from '@fortawesome/free-regular-svg-icons'
import { faCheck, faLock, faSpinner } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { onMounted, ref } from 'vue'

const { clearErrors, errorMessages, hasErrors, parseApiError } = useApiErrors()
const authStore = useAuthStore()

const isLoading = ref<boolean>(false)
const password = ref<string>('')
const confirmPassword = ref<string>('')
const username = ref<string>('')
const showPassword = ref<boolean>(false)

const handleLogin = async () => {
  isLoading.value = true

  if (password.value !== confirmPassword.value) {
    parseApiError({ message: 'Пароли не совпадают' })
    isLoading.value = false
    return
  }

  try {
    clearErrors()
    const registerBody: RegisterRequest = {
      username: username.value,
      password: password.value,
    }

    const response = await AuthService.registerUser(registerBody)

    if ('access_token' in response && 'refresh_token' in response) {
      const tokens: AuthTokens = response
      if (tokens.access_token && tokens.refresh_token) {
        await authStore.setTokens(tokens.access_token, tokens.refresh_token)
        setTimeout(() => {
          window.location.reload()
        }, 500)
      }
    } else {
      throw response
    }
  } catch (e) {
    parseApiError(e)
  } finally {
    isLoading.value = false
  }
}

onMounted(() => {
  document.title = 'Авторизация'
})
</script>

<template>
  <div
    class="min-h-screen bg-gradient-to-b from-slate-900 to-slate-950 flex items-center justify-center p-4"
  >
    <div class="h-full max-w-d bg-slate-800 rounded-xl shadow-2xl overflow-hidden">
      <div class="p-8">
        <div class="mb-8 flex items-center justify-center w-full">
          <h1 class="text-5xl items-center text-white font-bold">WebRTC Client</h1>
        </div>

        <div
          v-if="hasErrors"
          class="mb-4 p-4 bg-red-200 border border-red-400 text-red-700 rounded"
        >
          <ul>
            <li v-for="(error, index) in errorMessages" :key="index">{{ error }}</li>
          </ul>
        </div>

        <form @submit.prevent="handleLogin" class="space-y-6">
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <FontAwesomeIcon :icon="faUser" class="text-white"></FontAwesomeIcon>
            </div>
            <input
              v-model="username"
              class="w-full pl-10 pr-4 py-3 border text-white border-gray-300 rounded-lg focus:ring-4 focus:ring-blue-500 focus:border-transparent outline-none transition"
              placeholder="Логин"
              autocomplete="on"
              required
              type="text"
            />
          </div>

          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <FontAwesomeIcon :icon="faLock" class="text-white"></FontAwesomeIcon>
            </div>

            <input
              v-model="password"
              class="w-full pl-10 pr-4 py-3 border text-white border-gray-300 rounded-lg focus:ring-4 focus:ring-blue-500 focus:border-transparent outline-none transition"
              :type="showPassword ? 'text' : 'password'"
              autocomplete="current-password"
              placeholder="Пароль"
              required
            />

            <button
              type="button"
              @click="showPassword = !showPassword"
              class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-500 hover:text-gray-700"
              title="Показать/Скрыть пароль"
            >
              <FontAwesomeIcon :icon="showPassword ? faEyeSlash : faEye"></FontAwesomeIcon>
            </button>
          </div>

          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <FontAwesomeIcon :icon="faLock" class="text-white"></FontAwesomeIcon>
            </div>

            <input
              v-model="confirmPassword"
              class="w-full pl-10 pr-4 py-3 border text-white border-gray-300 rounded-lg focus:ring-4 focus:ring-blue-500 focus:border-transparent outline-none transition"
              :type="showPassword ? 'text' : 'password'"
              autocomplete="current-password"
              placeholder="Повторите пароль"
              required
            />

            <button
              type="button"
              @click="showPassword = !showPassword"
              class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-500 hover:text-gray-700"
              title="Показать/Скрыть пароль"
            >
              <FontAwesomeIcon :icon="showPassword ? faEyeSlash : faEye"></FontAwesomeIcon>
            </button>
          </div>

          <button
            type="submit"
            class="w-full bg-indigo-500 text-white py-3 rounded-lg font-semibold hover:bg-indigo-600 active:bg-indigo-400 transition-all duration-300 shadow-md hover:shadow-lg cursor-pointer disabled:cursor-not-allowed disabled:bg-indigo-300"
            title="Авторизоваться"
            :disabled="isLoading"
          >
            <FontAwesomeIcon
              :icon="isLoading ? faSpinner : faCheck"
              :spin="isLoading"
            ></FontAwesomeIcon>
            Зарегистрироваться
          </button>

          <div class="text-center">
            <RouterLink
              to="/auth/login"
              title="Авторизоваться"
              class="text-indigo-500 transition-all duration-300 hover:text-indigo-800"
              >Авторизоваться
            </RouterLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

// electron-client/src/pages/RegisterPage.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AuthService } from '@/api'
import type { RegisterRequest } from '@/api'
import { useAuthStore } from '@/stores/authStore'
import { useApiErrors } from '@/hooks/useApiErrors'
import { FontAwesomeIcon, faCheck, faEye, faEyeSlash, faLock, faSpinner, faUserOutline } from '@/icons'

export default function RegisterPage() {
  const navigate = useNavigate()
  const setTokens = useAuthStore((s) => s.setTokens)
  const { errorMessages, hasErrors, parseApiError, clearErrors } = useApiErrors()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (password !== confirmPassword) {
      parseApiError({ message: 'Пароли не совпадают' })
      return
    }
    setIsLoading(true)
    clearErrors()
    try {
      const body: RegisterRequest = { username, password }
      const response = await AuthService.registerUser(body)
      if (response && typeof response === 'object' && 'access_token' in response && 'refresh_token' in response) {
        const tokens = response as { access_token: string; refresh_token: string }
        if (tokens.access_token && tokens.refresh_token) {
          setTokens(tokens.access_token, tokens.refresh_token)
          navigate('/', { replace: true })
        }
      } else {
        parseApiError(response)
      }
    } catch (e) {
      parseApiError(e)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 to-slate-950 flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-slate-800 rounded-xl shadow-2xl overflow-hidden">
        <div className="p-8">
          <h1 className="text-3xl font-bold text-white text-center mb-8">WebRTC Client</h1>
          {hasErrors && (
            <div className="mb-4 p-4 bg-red-200 border border-red-400 text-red-700 rounded-lg">
              <ul>
                {errorMessages.map((msg, i) => (
                  <li key={i}>{msg}</li>
                ))}
              </ul>
            </div>
          )}
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="relative">
              <FontAwesomeIcon icon={faUserOutline} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="Логин"
                className="w-full pl-10 pr-4 py-3 border border-slate-600 rounded-lg bg-slate-700 text-white placeholder-slate-400 focus:ring-2 focus:ring-indigo-500 outline-none"
                required
              />
            </div>
            <div className="relative">
              <FontAwesomeIcon icon={faLock} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type={showPassword ? 'text' : 'password'}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Пароль"
                className="w-full pl-10 pr-12 py-3 border border-slate-600 rounded-lg bg-slate-700 text-white placeholder-slate-400 focus:ring-2 focus:ring-indigo-500 outline-none"
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-200"
              >
                <FontAwesomeIcon icon={showPassword ? faEyeSlash : faEye} />
              </button>
            </div>
            <div className="relative">
              <FontAwesomeIcon icon={faLock} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type={showPassword ? 'text' : 'password'}
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                placeholder="Повторите пароль"
                className="w-full pl-10 pr-4 py-3 border border-slate-600 rounded-lg bg-slate-700 text-white placeholder-slate-400 focus:ring-2 focus:ring-indigo-500 outline-none"
                required
              />
            </div>
            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-indigo-500 hover:bg-indigo-600 disabled:bg-indigo-300 text-white py-3 rounded-lg font-semibold transition-colors disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <FontAwesomeIcon icon={isLoading ? faSpinner : faCheck} spin={isLoading} />
              {isLoading ? 'Регистрация...' : 'Зарегистрироваться'}
            </button>
            <p className="text-center">
              <Link to="/auth/login" className="text-indigo-400 hover:text-indigo-300">
                Войти
              </Link>
            </p>
          </form>
        </div>
      </div>
    </div>
  )
}
